/** Launch library of teaching question sets. Bank sets are not deletable. */

function q(prompts) {
  return prompts.map((item, index) => {
    if (typeof item === 'string') {
      return {
        id: `p${index + 1}`,
        type: 'short',
        prompt: item,
        options: [],
        correctAnswer: '',
      };
    }
    const prompt = String(item?.prompt || '').trim();
    const helper = String(item?.helper || item?.descriptor || '').trim().slice(0, 240);
    return {
      id: `p${index + 1}`,
      type: 'short',
      prompt,
      options: [],
      correctAnswer: '',
      ...(helper ? { helper } : {}),
    };
  }).filter((question) => question.prompt);
}

function set(def) {
  return {
    ...def,
    bank: true,
    questions: q(def.prompts),
  };
}

export const SUBJECTS = ['English', 'HASS', 'Maths', 'Science', 'General'];
export const YEAR_BANDS = ['5–6', '7–8', '9–10', '11–12'];

export const QUESTION_SET_BANK = [
  // English — curated writing library + literature / poetry / persuasive / essay
  set({
    id: 'bank-eng-01',
    name: 'Build a Strong Paragraph',
    subject: 'English',
    years: '5–6',
    skill: 'Writing',
    minutes: 10,
    prompts: [
      'What is the main idea of your paragraph?',
      'Write a sentence that clearly introduces that idea.',
      'Add an example, fact or detail.',
      'Explain how your example supports your main idea.',
      'Write a final sentence that wraps up the paragraph.',
      'Reread it. Which sentence could you make clearer?',
    ],
  }),
  set({
    id: 'bank-eng-02',
    name: 'Build a Narrative Paragraph',
    subject: 'English',
    years: '5–6',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'Where is your character?',
      'What is happening right now?',
      'Add something your character can see, hear or feel.',
      'What does your character do?',
      'What happens next?',
      'Reread your paragraph. Add or improve one detail.',
    ],
  }),

  // Narrative / creative coaching
  set({
    id: 'bank-eng-cw-01',
    name: 'Show, Don’t Tell',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'Find a sentence that tells the reader how the character feels.',
      'Remove the emotion word.',
      'What could the character do physically instead?',
      'Add one small body-language or sensory detail.',
      'Can the reader now infer the feeling without being told?',
    ],
  }),
  set({
    id: 'bank-eng-cw-02',
    name: 'Character Through Action',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'What does your character want right now?',
      'What action could reveal that want?',
      'Add one gesture, habit or choice that reveals character.',
      'Can you remove an explanation and let the action do the work?',
      'What should the reader infer?',
    ],
  }),
  set({
    id: 'bank-eng-cw-03',
    name: 'Dialogue with Purpose',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'What does each character want from this conversation?',
      'Cut one greeting, filler line or unnecessary explanation.',
      'What is one thing the character will not say directly?',
      'Add an action or reaction that creates subtext.',
      'Do the characters sound different from each other?',
    ],
  }),
  set({
    id: 'bank-eng-cw-04',
    name: 'Build Tension',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 12,
    prompts: [
      'What does the character want?',
      'What is stopping them?',
      'Where could you delay an action or reveal?',
      'What could you withhold from the reader?',
      'Add one small signal that something is wrong.',
      'End with the pressure still unresolved.',
    ],
  }),
  set({
    id: 'bank-eng-cw-05',
    name: 'Control the Pace',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'Which moment deserves the most attention?',
      'Slow it using action, sensory detail or thought.',
      'Which part could be compressed or skipped?',
      'Where could a short sentence create impact?',
      'Where could a paragraph break change the pace?',
    ],
  }),
  set({
    id: 'bank-eng-cw-06',
    name: 'Make the Setting Work',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'What should the setting make the reader feel?',
      'Replace one general description with a precise detail.',
      'Add sound, texture, smell or temperature.',
      'How can the character interact with the setting?',
      'Which detail could reinforce mood, tension or theme?',
    ],
  }),
  set({
    id: 'bank-eng-cw-07',
    name: 'Sensory Detail with Purpose',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'Which sense matters most in this moment?',
      'What precise detail would the character actually notice?',
      'How does this detail affect mood or meaning?',
      'Remove one sensory detail that adds nothing.',
      'Make one remaining detail do more work.',
    ],
  }),
  set({
    id: 'bank-eng-cw-08',
    name: 'Strong Openings',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'How late can you enter the scene?',
      'Can you begin with action, image, voice or problem?',
      'What backstory can wait?',
      'What question or tension should the opening create?',
      'Rewrite the first sentence so it earns the second.',
    ],
  }),
  set({
    id: 'bank-eng-cw-09',
    name: 'Strong Endings',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'What has changed by the end?',
      'Which final sentence explains too much?',
      'Could an image, action or line of dialogue carry the meaning?',
      'What should the reader feel or wonder?',
      'Is the ending stronger if you cut the explanation?',
    ],
  }),
  set({
    id: 'bank-eng-cw-10',
    name: 'Sentence Craft & Precision',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'Replace one weak verb with a precise one.',
      'Make one vague noun or description specific.',
      'Change one predictable sentence opening.',
      'Split or reshape one overloaded sentence.',
      'Remove words that add length but not meaning.',
      'Read it aloud. Where could the rhythm improve?',
    ],
  }),
  set({
    id: 'bank-eng-cw-11',
    name: 'Narrative Voice & Point of View',
    subject: 'English',
    years: '9–12',
    skill: 'Creative writing',
    minutes: 12,
    prompts: [
      'Who is telling this moment?',
      'What can this narrator know?',
      'What would this character notice first?',
      'Does the language sound like this narrator?',
      'Find one sentence that breaks the point of view.',
      'Rewrite it through the narrator’s perspective.',
    ],
  }),

  // Analytical coaching
  set({
    id: 'bank-eng-an-01',
    name: 'Stop Retelling the Plot',
    subject: 'English',
    years: '7–10',
    skill: 'Analytical writing',
    minutes: 10,
    prompts: [
      'Which sentence simply tells me what happened?',
      'What does this event reveal?',
      'Why has the author included it?',
      'What idea does it develop?',
      'Rewrite the point so it makes an argument rather than retelling.',
    ],
  }),
  set({
    id: 'bank-eng-an-02',
    name: 'Make a Real Analytical Claim',
    subject: 'English',
    years: '7–10',
    skill: 'Analytical writing',
    minutes: 10,
    prompts: [
      'What are you actually arguing?',
      'Could someone reasonably disagree with this?',
      'What does the text suggest, rather than simply show?',
      'Make the claim more specific.',
      'Make the claim answer the question.',
    ],
  }),
  set({
    id: 'bank-eng-an-03',
    name: 'Strong Topic Sentences',
    subject: 'English',
    years: '7–10',
    skill: 'Analytical writing',
    minutes: 10,
    prompts: [
      'What is this paragraph arguing?',
      'Which key word from the question should it address?',
      'Remove plot summary from the topic sentence.',
      'Make the sentence interpretive rather than descriptive.',
      'Does it clearly support your overall thesis?',
    ],
  }),
  set({
    id: 'bank-eng-an-04',
    name: 'Choose Better Evidence',
    subject: 'English',
    years: '7–10',
    skill: 'Analytical writing',
    minutes: 10,
    prompts: [
      'Which evidence best proves your point?',
      'Is the quote too long?',
      'Which word or phrase carries the strongest meaning?',
      'Could a more precise example work better?',
      'Why is this evidence stronger than another option?',
    ],
  }),
  set({
    id: 'bank-eng-an-05',
    name: 'Unpack the Quote',
    subject: 'English',
    years: '7–10',
    skill: 'Analytical writing',
    minutes: 10,
    prompts: [
      'Which word or phrase matters most?',
      'What does it suggest?',
      'What connotations does it carry?',
      'Why might the author have chosen it?',
      'How does it support your argument?',
    ],
  }),
  set({
    id: 'bank-eng-an-06',
    name: 'Authorial Choices',
    subject: 'English',
    years: '9–12',
    skill: 'Analytical writing',
    minutes: 12,
    prompts: [
      'What deliberate choice has the author made?',
      'Which aesthetic feature or literary device is being used?',
      'How does it shape meaning?',
      'Why is this choice effective here?',
      'How does it support your interpretation?',
    ],
  }),
  set({
    id: 'bank-eng-an-07',
    name: 'Audience Positioning',
    subject: 'English',
    years: '9–12',
    skill: 'Analytical writing',
    minutes: 10,
    prompts: [
      'How is the audience positioned to respond?',
      'What might the audience think, feel, question or believe?',
      'Which authorial choice creates this response?',
      'Why does this response matter?',
      'How does audience positioning support the author’s purpose?',
    ],
  }),
  set({
    id: 'bank-eng-an-08',
    name: 'Culture, Values & Beliefs',
    subject: 'English',
    years: '9–12',
    skill: 'Analytical writing',
    minutes: 12,
    prompts: [
      'What assumption, attitude, value or belief is represented here?',
      'Is the text reinforcing, questioning or challenging it?',
      'Which character, event or authorial choice reveals this?',
      'How might different audiences respond?',
      'How does this shape the text’s wider meaning?',
    ],
  }),
  set({
    id: 'bank-eng-an-09',
    name: 'Higher Insight',
    subject: 'English',
    years: '9–12',
    skill: 'Analytical writing',
    minutes: 10,
    prompts: [
      'What bigger idea does this reveal?',
      'What does this suggest about people, society, culture, identity, power, values or the wider issue?',
      'Why does this matter beyond this single moment?',
      'Is there a contradiction, tension or complexity here?',
      'How does this deepen your interpretation?',
    ],
  }),
  set({
    id: 'bank-eng-an-10',
    name: 'Link Evidence to Argument',
    subject: 'English',
    years: '7–10',
    skill: 'Analytical writing',
    minutes: 10,
    prompts: [
      'How does this evidence prove your point?',
      'What part of your argument does it strengthen?',
      'What key idea does it connect to?',
      'Rewrite the final sentence so it clearly returns to the argument.',
      'Does the paragraph still answer the question?',
    ],
  }),
  set({
    id: 'bank-eng-an-11',
    name: 'Extend & Synthesise',
    subject: 'English',
    years: '9–12',
    skill: 'Analytical writing',
    minutes: 12,
    prompts: [
      'What second piece of evidence could develop this idea?',
      'Does it reinforce, contrast or complicate the first example?',
      'What new layer does it add?',
      'Can you compare the two examples rather than discuss them separately?',
      'What stronger conclusion can you now draw?',
    ],
  }),
  set({
    id: 'bank-eng-teacher',
    name: 'TEACHER Analytical Paragraph',
    subject: 'English',
    years: '9–12',
    skill: 'Analytical writing',
    minutes: 15,
    note: 'Flagship exam scaffold: Topic, Evidence, Author+Audience, Culture, Higher insight, Extend, Return.',
    prompts: [
      {
        prompt: 'T — Topic / Thesis: What is your paragraph arguing?',
        helper: 'Write a clear point that answers the question.',
      },
      {
        prompt: 'E — Evidence: What evidence best proves your point?',
        helper: 'Use a precise quote, example or textual detail.',
      },
      {
        prompt: 'A — Author + Audience: What has the author done, and how does it position the audience?',
        helper: 'Analyse an aesthetic feature, literary device, language or structural choice, then explain what it makes the audience think, feel, notice or believe.',
      },
      {
        prompt: 'C — Culture: What assumptions, attitudes, values or beliefs are represented?',
        helper: 'Explain what the text reinforces, questions or challenges.',
      },
      {
        prompt: 'H — Human / Higher Insight: What bigger idea does this reveal?',
        helper: 'Think beyond the quote: people, society, culture, identity, power, values or the wider issue.',
      },
      {
        prompt: 'E — Extend: What further evidence develops or complicates your idea?',
        helper: 'Add a second example that strengthens, contrasts or deepens the analysis.',
      },
      {
        prompt: 'R — Return: How does this return to your argument?',
        helper: 'Tie the paragraph back to the question and your overall thesis.',
      },
    ],
  }),

  // Keep junior analytical scaffold (different year/purpose from TEACHER)
  set({
    id: 'bank-eng-05',
    name: 'Analytical Paragraph Builder',
    subject: 'English',
    years: '7–8',
    skill: 'Text analysis',
    minutes: 12,
    prompts: [
      'What is your main point about the text?',
      'Choose evidence that supports your point.',
      'Which important word, phrase or technique can you zoom in on?',
      'What does it suggest?',
      'What does the author want the reader to think or feel?',
      'Connect your analysis back to your main point.',
    ],
  }),

  // Literature / poetry / persuasive / essay — preserved
  set({
    id: 'bank-eng-08',
    name: 'Character Analysis',
    subject: 'English',
    years: '7–8',
    skill: 'Literature',
    minutes: 10,
    prompts: [
      'What do we learn about this character?',
      'Choose a moment that reveals this.',
      'What does the character say, do or think?',
      'Which detail is particularly important?',
      'What does this suggest about the character?',
      'Does our understanding of the character change?',
    ],
  }),
  set({
    id: 'bank-eng-09',
    name: 'Theme Analysis',
    subject: 'English',
    years: '9–10',
    skill: 'Literature',
    minutes: 12,
    prompts: [
      'What important idea is the text exploring?',
      'Where can you see this idea in the text?',
      'Which character, event, image or technique helps develop it?',
      'How does the idea change or become more complex?',
      'What might the author be encouraging the audience to consider?',
      'How does this idea connect to the text as a whole?',
    ],
  }),
  set({
    id: 'bank-eng-10',
    name: 'Poetry Close Reading',
    subject: 'English',
    years: '7–8',
    skill: 'Poetry',
    minutes: 10,
    prompts: [
      'What seems to be happening in the poem?',
      'Which word or image stands out to you?',
      'What technique can you identify?',
      'What feeling or idea does it create?',
      'Why might the poet have chosen it?',
      'What do you think the poem is saying overall?',
    ],
  }),
  set({
    id: 'bank-eng-11',
    name: 'Poetry Analysis',
    subject: 'English',
    years: '9–10',
    skill: 'Poetry',
    minutes: 12,
    prompts: [
      'What interpretation of the poem are you developing?',
      'Which image, word pattern or structural feature is significant?',
      'What technique is being used?',
      'How does this choice shape tone or meaning?',
      'How does it influence the reader?',
      "How does this feature connect to the poem's broader ideas?",
    ],
  }),
  set({
    id: 'bank-eng-12',
    name: 'Build a Persuasive Paragraph',
    subject: 'English',
    years: '7–8',
    skill: 'Persuasive writing',
    minutes: 10,
    prompts: [
      'What do you want your audience to believe?',
      'Give your strongest reason.',
      'Add evidence, an example or an explanation.',
      'Choose persuasive language deliberately.',
      'Explain why this issue matters.',
      'Finish by reinforcing your argument.',
    ],
  }),
  set({
    id: 'bank-eng-13',
    name: 'Argument & Counterargument',
    subject: 'English',
    years: '9–10',
    skill: 'Persuasive writing',
    minutes: 12,
    prompts: [
      'What is your main argument?',
      'What evidence supports it?',
      'What might someone who disagrees say?',
      'Why might they hold that view?',
      'How could you respond to that argument?',
      'How does addressing the opposing view strengthen your position?',
    ],
  }),
  set({
    id: 'bank-eng-14',
    name: 'Plan a Senior Essay',
    subject: 'English',
    years: '11–12',
    skill: 'Essay writing',
    minutes: 12,
    prompts: [
      'What is your overall contention or interpretation?',
      'What will each body paragraph argue?',
      'Which evidence will best support each argument?',
      'How will the paragraphs build on one another?',
      'What complexity, tension or alternative interpretation should you address?',
      'What should the reader understand by the end of the essay?',
    ],
  }),

  // HASS — 8
  set({
    id: 'bank-hass-15',
    name: 'Source Detective',
    subject: 'HASS',
    years: '5–6',
    skill: 'History',
    minutes: 10,
    prompts: [
      'What kind of source is this?',
      'Who created it?',
      'When was it created?',
      'What does it show or tell us?',
      'Why might it have been created?',
      'What can this source help us learn?',
    ],
  }),
  set({
    id: 'bank-hass-16',
    name: 'Different Views of an Event',
    subject: 'HASS',
    years: '5–6',
    skill: 'History / Civics',
    minutes: 10,
    prompts: [
      'Who are the people or groups involved?',
      'What does each person or group think?',
      'Why might their views be different?',
      'What evidence tells you this?',
      'Whose point of view might be missing?',
      'Why is it useful to consider more than one point of view?',
    ],
  }),
  set({
    id: 'bank-hass-17',
    name: 'IOPCAM Source Analysis',
    subject: 'HASS',
    years: '7–8',
    skill: 'History',
    minutes: 12,
    prompts: [
      'Information: What does the source tell or show us?',
      'Origin: Who created it, and when?',
      'Purpose: Why was it created?',
      'Context: What was happening at the time?',
      'Audience: Who was it created for?',
      'Message: What main idea or message is being communicated?',
    ],
  }),
  set({
    id: 'bank-hass-18',
    name: 'Reliability & Usefulness',
    subject: 'HASS',
    years: '9–10',
    skill: 'History',
    minutes: 12,
    prompts: [
      'What claim or message does the source present?',
      'Who created it?',
      'What was their purpose?',
      'What might influence their perspective?',
      'What makes the source useful?',
      'What are its limitations?',
      'What other evidence would help you check it?',
    ],
  }),
  set({
    id: 'bank-hass-19',
    name: 'Senior Source Evaluation',
    subject: 'HASS',
    years: '11–12',
    skill: 'History',
    minutes: 12,
    prompts: [
      'What perspective does the source construct?',
      'How do its origin and context shape that perspective?',
      'How does purpose influence what is included or omitted?',
      'Which evidence within the source is most significant?',
      'What limitations affect its usefulness?',
      'What evidence could corroborate or challenge it?',
    ],
  }),
  set({
    id: 'bank-hass-20',
    name: 'Cause & Consequence',
    subject: 'HASS',
    years: '7–10',
    skill: 'History',
    minutes: 10,
    prompts: [
      'What event or change are you examining?',
      'What were the main causes?',
      'Which cause was most significant?',
      'Why?',
      'What were the immediate consequences?',
      'What were the longer-term consequences?',
    ],
  }),
  set({
    id: 'bank-hass-21',
    name: 'Continuity & Change',
    subject: 'HASS',
    years: '7–10',
    skill: 'History',
    minutes: 10,
    prompts: [
      'What changed during this period?',
      'What stayed the same?',
      'Who experienced the greatest change?',
      'What caused the change?',
      'Was the change sudden or gradual?',
      'Why was the change significant?',
    ],
  }),
  set({
    id: 'bank-hass-22',
    name: 'Interpret Geographic Data',
    subject: 'HASS',
    years: '7–10',
    skill: 'Geography',
    minutes: 10,
    prompts: [
      'What does the map, graph or data show?',
      'What spatial pattern can you identify?',
      'Where is the pattern strongest or weakest?',
      'Is anything unusual?',
      'What geographic factors might explain the pattern?',
      'What conclusion is supported by the evidence?',
    ],
  }),

  // Maths — 8
  set({
    id: 'bank-maths-23',
    name: 'Understand the Problem',
    subject: 'Maths',
    years: '5–6',
    skill: 'Problem solving',
    minutes: 8,
    prompts: [
      'What is the problem asking you to find?',
      'Which information will help you solve it?',
      'What operation or strategy might work?',
      'Estimate what you think the answer might be.',
      'Solve the problem.',
      'Does your answer make sense?',
    ],
  }),
  set({
    id: 'bank-maths-24',
    name: 'Problem-Solving Routine',
    subject: 'Maths',
    years: '7–8',
    skill: 'Problem solving',
    minutes: 12,
    prompts: [
      'What is the unknown?',
      'What useful information have you been given?',
      'Is any information unnecessary?',
      'Choose a strategy.',
      'Show your working clearly.',
      'Check your answer.',
      'Explain your solution in one sentence.',
    ],
  }),
  set({
    id: 'bank-maths-25',
    name: 'Complex Problem Solving',
    subject: 'Maths',
    years: '9–10',
    skill: 'Problem solving',
    minutes: 15,
    prompts: [
      'What quantities or variables are involved?',
      'What relationships can you identify?',
      'Which mathematical idea, formula or strategy applies?',
      'Break the problem into logical steps.',
      'Solve and justify your method.',
      'Check your result against the original problem.',
      'Are there any limitations or assumptions?',
    ],
  }),
  set({
    id: 'bank-maths-26',
    name: 'Mathematical Modelling',
    subject: 'Maths',
    years: '11–12',
    skill: 'Senior mathematics',
    minutes: 18,
    prompts: [
      'Define the problem clearly.',
      'What assumptions will you need to make?',
      'Identify the variables and relationships involved.',
      'Develop an appropriate mathematical model.',
      'Solve the model.',
      'Interpret your result in the original context.',
      'Test whether the solution is reasonable.',
      'Evaluate the limitations of the model.',
    ],
  }),
  set({
    id: 'bank-maths-27',
    name: 'Find the Error',
    subject: 'Maths',
    years: '7–10',
    skill: 'Mathematical reasoning',
    minutes: 10,
    note: 'Works best with a worked example on the board.',
    prompts: [
      'Study the working carefully.',
      'Where does the first error occur?',
      'What do you think the student was trying to do?',
      'Why is that step incorrect?',
      'Show the correct step.',
      'Continue the solution from there.',
    ],
  }),
  set({
    id: 'bank-maths-28',
    name: 'Explain Your Method',
    subject: 'Maths',
    years: '7–10',
    skill: 'Mathematical reasoning',
    minutes: 10,
    prompts: [
      'What strategy did you use?',
      'Why did you choose it?',
      'Show the important steps.',
      'Which step required the most thinking?',
      'How did you check your answer?',
      'Explain your method so another student could follow it.',
    ],
  }),
  set({
    id: 'bank-maths-29',
    name: 'Compare Two Strategies',
    subject: 'Maths',
    years: '7–10',
    skill: 'Mathematical reasoning',
    minutes: 10,
    prompts: [
      'How does Strategy A work?',
      'How does Strategy B work?',
      'What do the strategies have in common?',
      'How are they different?',
      'Which is more efficient for this problem?',
      'When might the other strategy be more useful?',
    ],
  }),
  set({
    id: 'bank-maths-30',
    name: 'Read the Data',
    subject: 'Maths',
    years: '7–10',
    skill: 'Data',
    minutes: 10,
    prompts: [
      'What does the graph or table represent?',
      'What pattern can you see?',
      'What comparison can you make?',
      'Is there anything unusual?',
      'What calculation could help you understand the data?',
      'What conclusion is supported by the data?',
    ],
  }),

  // Science — 8
  set({
    id: 'bank-sci-31',
    name: 'Predict–Observe–Explain',
    subject: 'Science',
    years: '5–8',
    skill: 'Scientific thinking',
    minutes: 10,
    prompts: [
      'What do you predict will happen?',
      'Why do you think that?',
      'What actually happened?',
      'Was your prediction supported?',
      'What scientific idea could explain the result?',
    ],
  }),
  set({
    id: 'bank-sci-32',
    name: 'Identify the Variables',
    subject: 'Science',
    years: '7–8',
    skill: 'Investigations',
    minutes: 8,
    prompts: [
      'What question are you investigating?',
      'What will you change?',
      'What will you measure?',
      'What needs to stay the same?',
      'Why do these things need to stay the same?',
      'How will you make the test fair?',
    ],
  }),
  set({
    id: 'bank-sci-33',
    name: 'Plan an Investigation',
    subject: 'Science',
    years: '7–8',
    skill: 'Investigations',
    minutes: 12,
    prompts: [
      'What question are you investigating?',
      'What is your hypothesis?',
      'What will you change?',
      'What will you measure?',
      'What will you keep the same?',
      'What equipment will you need?',
      'What data will you collect?',
    ],
  }),
  set({
    id: 'bank-sci-34',
    name: 'Claim–Evidence–Reasoning',
    subject: 'Science',
    years: '9–10',
    skill: 'Scientific explanation',
    minutes: 10,
    prompts: [
      'What claim can you make?',
      'Which evidence supports the claim?',
      'Which scientific concept helps explain the evidence?',
      'How does the evidence support your claim?',
      'Is there any evidence that does not fit?',
      'Write a clear conclusion.',
    ],
  }),
  set({
    id: 'bank-sci-35',
    name: 'Interpret Scientific Data',
    subject: 'Science',
    years: '7–10',
    skill: 'Data analysis',
    minutes: 10,
    prompts: [
      'What trend or pattern can you identify?',
      'Which evidence supports your observation?',
      'Are there any unusual results?',
      'How strong is the pattern?',
      'What scientific explanation could account for it?',
      'What conclusion can you draw?',
    ],
  }),
  set({
    id: 'bank-sci-36',
    name: 'Evaluate an Investigation',
    subject: 'Science',
    years: '9–10',
    skill: 'Investigations',
    minutes: 12,
    prompts: [
      'How reliable are the results?',
      'Are there any unusual or inconsistent results?',
      'What sources of error may have affected the investigation?',
      'Was the method suitable for answering the question?',
      'What could be improved?',
      'What further investigation would strengthen the conclusion?',
    ],
  }),
  set({
    id: 'bank-sci-37',
    name: 'Build a Scientific Explanation',
    subject: 'Science',
    years: '7–10',
    skill: 'Scientific writing',
    minutes: 10,
    prompts: [
      'What phenomenon are you explaining?',
      'Which scientific ideas are relevant?',
      'What evidence or example can you use?',
      'Explain how the evidence connects to the science.',
      'Use scientific vocabulary accurately.',
      'Finish with a clear explanation of why the phenomenon occurs.',
    ],
  }),
  set({
    id: 'bank-sci-38',
    name: 'Evaluate Scientific Evidence',
    subject: 'Science',
    years: '11–12',
    skill: 'Senior science',
    minutes: 15,
    prompts: [
      'What claim or conclusion is being made?',
      'What evidence supports it?',
      'How reliable is the evidence?',
      'What uncertainty, error or limitation is present?',
      'How valid is the conclusion?',
      'Are there alternative explanations?',
      'What additional evidence would strengthen the claim?',
    ],
  }),

  // General — 10
  set({
    id: 'bank-gen-39',
    name: 'Retrieval Warm-Up',
    subject: 'General',
    years: 'All',
    skill: 'Lesson opener',
    minutes: 8,
    prompts: [
      'What can you remember from the last lesson?',
      'Write three important ideas.',
      'Give one example.',
      'Which idea are you least certain about?',
      'Write one question you still have.',
    ],
  }),
  set({
    id: 'bank-gen-40',
    name: 'Confidence Check',
    subject: 'General',
    years: 'All',
    skill: 'Formative check',
    minutes: 5,
    prompts: [
      'How confident are you right now? 1–5',
      'What part feels easiest?',
      'What part are you unsure about?',
      'What would help move your confidence up one point?',
    ],
  }),
  set({
    id: 'bank-gen-41',
    name: 'Find the Misconception',
    subject: 'General',
    years: 'All',
    skill: 'Understanding check',
    minutes: 8,
    note: 'Works best with a statement or example on the board.',
    prompts: [
      'Read the statement or example carefully.',
      'What do you think is incorrect?',
      'Explain why.',
      'What should the correct idea be?',
      'What mistake might have caused the misunderstanding?',
    ],
  }),
  set({
    id: 'bank-gen-42',
    name: 'Exit Understanding Check',
    subject: 'General',
    years: 'All',
    skill: 'Lesson close',
    minutes: 6,
    prompts: [
      'What is the most important thing you learned?',
      'Explain it in your own words.',
      'Give an example.',
      'What can you now do that you could not do before?',
      'What are you still unsure about?',
    ],
  }),
  set({
    id: 'bank-gen-43',
    name: 'Peer Feedback',
    subject: 'General',
    years: '7–12',
    skill: 'Feedback',
    minutes: 8,
    note: 'Works best when students can see a peer’s work.',
    prompts: [
      'What is working well in this piece?',
      'Point to one specific example.',
      'Where could the writer make their meaning clearer?',
      'What is one question you have for the writer?',
      'Give one useful suggestion for the next draft.',
    ],
  }),
  set({
    id: 'bank-gen-44',
    name: 'Draft → Feedback → Redraft',
    subject: 'General',
    years: '7–12',
    skill: 'Writing & feedback',
    minutes: 12,
    note: 'Use after you have commented, or as a structure for Inbox feedback.',
    prompts: [
      'Identify the section you want feedback on.',
      "Read your teacher's comment or note.",
      'What is the feedback asking you to improve?',
      'Explain what you plan to change.',
      'Make the revision.',
      'How has your revision improved the work?',
    ],
  }),
  set({
    id: 'bank-gen-45',
    name: 'Unpack a Key Word',
    subject: 'General',
    years: '5–10',
    skill: 'Vocabulary',
    minutes: 8,
    prompts: [
      'What do you think this word means?',
      'Put the meaning into your own words.',
      'Use the word in a sentence.',
      'What other words have a similar meaning?',
      'What is an example of it?',
      "What is something people might think it means, but it doesn't?",
    ],
  }),
  set({
    id: 'bank-gen-46',
    name: 'Compare & Contrast',
    subject: 'General',
    years: '5–10',
    skill: 'Thinking routine',
    minutes: 8,
    prompts: [
      'What do the two things have in common?',
      'What is one important difference?',
      'Find another difference.',
      'Which difference matters most?',
      'Why?',
      'What conclusion can you make from the comparison?',
    ],
  }),
  set({
    id: 'bank-gen-47',
    name: 'Independent Work Check-In',
    subject: 'General',
    years: 'All',
    skill: 'Live monitoring',
    minutes: 5,
    prompts: [
      'What are you working on right now?',
      'What have you completed?',
      'What are you working on next?',
      'Are you stuck anywhere?',
      'If you are stuck, explain exactly where.',
      'What do you need from your teacher?',
    ],
  }),
  set({
    id: 'bank-gen-48',
    name: 'Teach It Back',
    subject: 'General',
    years: 'All',
    skill: 'Understanding',
    minutes: 8,
    prompts: [
      'Explain the idea as if you were teaching someone who missed the lesson.',
      'What are the most important things they need to know?',
      'Give an example.',
      'What mistake should they avoid?',
      'What question would you ask to check whether they understood?',
    ],
  }),
];

const YEAR_ORDER = ['5–6', '7–8', '9–10', '11–12'];

function expandYears(label) {
  const raw = String(label || '').replace(/-/g, '–').trim();
  if (!raw || raw === 'All') return new Set(YEAR_ORDER);
  if (YEAR_ORDER.includes(raw)) return new Set([raw]);
  const match = raw.match(/^(\d+)–(\d+)$/);
  if (!match) return new Set(YEAR_ORDER);
  const start = Number(match[1]);
  const end = Number(match[2]);
  const covered = new Set();
  for (const band of YEAR_ORDER) {
    const [a, b] = band.split('–').map(Number);
    if (a <= end && b >= start) covered.add(band);
  }
  return covered.size ? covered : new Set(YEAR_ORDER);
}

export function setMatchesFilters(set, subject, yearBand) {
  if (subject && subject !== 'All' && set.subject !== subject) return false;
  if (!yearBand || yearBand === 'All') return true;
  return expandYears(set.years).has(yearBand);
}

export function formatSetMeta(set) {
  const years = set.years === 'All' ? 'All years' : `Years ${set.years}`;
  const mins = set.minutes ? `~${set.minutes} min` : '';
  return [set.subject, years, set.skill, mins].filter(Boolean).join(' · ');
}
