/** Launch library of teaching question sets. Bank sets are not deletable. */

function q(prompts) {
  return prompts.map((item, index) => {
    if (typeof item === 'string') {
      return {
        id: `p${index + 1}`,
        type: 'short',
        prompt: item,
        options: [],
        correctAnswer: '',
      };
    }
    const prompt = String(item?.prompt || '').trim();
    const helper = String(item?.helper || item?.descriptor || '').trim().slice(0, 240);
    return {
      id: `p${index + 1}`,
      type: 'short',
      prompt,
      options: [],
      correctAnswer: '',
      ...(helper ? { helper } : {}),
    };
  }).filter((question) => question.prompt);
}

function set(def) {
  return {
    ...def,
    bank: true,
    questions: q(def.prompts),
  };
}

export const SUBJECTS = ['English', 'HASS', 'Maths', 'Science', 'General'];
export const YEAR_BANDS = ['5–6', '7–8', '9–10', '11–12'];

export const QUESTION_SET_BANK = [
  // English — curated writing library + literature / poetry / persuasive / essay
  set({
    id: 'bank-eng-01',
    name: 'Build a Strong Paragraph',
    subject: 'English',
    years: '5–6',
    skill: 'Writing',
    minutes: 10,
    prompts: [
      'What is the one main idea of this paragraph?',
      'Write a first sentence that puts that idea on the table.',
      'Add one example, fact or detail that proves it.',
      'Explain how that example supports your idea.',
      'Write a last sentence that wraps the paragraph shut.',
      'Reread. Which sentence would confuse a classmate?',
    ],
  }),
  set({
    id: 'bank-eng-02',
    name: 'Build a Narrative Paragraph',
    subject: 'English',
    years: '5–6',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'Where is your character right now?',
      'What is happening in this exact moment?',
      'Add one thing they can see, hear or feel.',
      'What does your character do next?',
      'What happens because of that action?',
      'Reread. Upgrade one weak detail.',
    ],
  }),

  // Narrative / creative coaching
  set({
    id: 'bank-eng-cw-01',
    name: 'Show, Don’t Tell',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'Find a sentence that tells the reader how the character feels.',
      'Remove the emotion word.',
      'What could the character do physically instead?',
      'Add one small body-language or sensory detail.',
      'Can the reader now infer the feeling without being told?',
    ],
  }),
  set({
    id: 'bank-eng-cw-02',
    name: 'Character Through Action',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'What does your character want right now?',
      'What action could reveal that want?',
      'Add one gesture, habit or choice that reveals character.',
      'Can you remove an explanation and let the action do the work?',
      'What should the reader infer?',
    ],
  }),
  set({
    id: 'bank-eng-cw-03',
    name: 'Dialogue with Purpose',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'What does each character want from this conversation?',
      'Cut one greeting, filler line or unnecessary explanation.',
      'What is one thing the character will not say directly?',
      'Add an action or reaction that creates subtext.',
      'Do the characters sound different from each other?',
    ],
  }),
  set({
    id: 'bank-eng-cw-04',
    name: 'Build Tension',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 12,
    prompts: [
      'What does the character want?',
      'What is stopping them?',
      'Where could you delay an action or reveal?',
      'What could you withhold from the reader?',
      'Add one small signal that something is wrong.',
      'End with the pressure still unresolved.',
    ],
  }),
  set({
    id: 'bank-eng-cw-05',
    name: 'Control the Pace',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'Which moment deserves the most attention?',
      'Slow it using action, sensory detail or thought.',
      'Which part could be compressed or skipped?',
      'Where could a short sentence create impact?',
      'Where could a paragraph break change the pace?',
    ],
  }),
  set({
    id: 'bank-eng-cw-06',
    name: 'Make the Setting Work',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'What should the setting make the reader feel?',
      'Replace one general description with a precise detail.',
      'Add sound, texture, smell or temperature.',
      'How can the character interact with the setting?',
      'Which detail could reinforce mood, tension or theme?',
    ],
  }),
  set({
    id: 'bank-eng-cw-07',
    name: 'Sensory Detail with Purpose',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'Which sense matters most in this moment?',
      'What precise detail would the character actually notice?',
      'How does this detail affect mood or meaning?',
      'Remove one sensory detail that adds nothing.',
      'Make one remaining detail do more work.',
    ],
  }),
  set({
    id: 'bank-eng-cw-08',
    name: 'Strong Openings',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'How late can you enter the scene?',
      'Can you begin with action, image, voice or problem?',
      'What backstory can wait?',
      'What question or tension should the opening create?',
      'Rewrite the first sentence so it earns the second.',
    ],
  }),
  set({
    id: 'bank-eng-cw-09',
    name: 'Strong Endings',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'What has changed by the end?',
      'Which final sentence explains too much?',
      'Could an image, action or line of dialogue carry the meaning?',
      'What should the reader feel or wonder?',
      'Is the ending stronger if you cut the explanation?',
    ],
  }),
  set({
    id: 'bank-eng-cw-10',
    name: 'Sentence Craft & Precision',
    subject: 'English',
    years: '7–10',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'Replace one weak verb with a precise one.',
      'Make one vague noun or description specific.',
      'Change one predictable sentence opening.',
      'Split or reshape one overloaded sentence.',
      'Remove words that add length but not meaning.',
      'Read it aloud. Where could the rhythm improve?',
    ],
  }),
  set({
    id: 'bank-eng-cw-11',
    name: 'Narrative Voice & Point of View',
    subject: 'English',
    years: '9–12',
    skill: 'Creative writing',
    minutes: 12,
    prompts: [
      'Who is telling this moment?',
      'What can this narrator know?',
      'What would this character notice first?',
      'Does the language sound like this narrator?',
      'Find one sentence that breaks the point of view.',
      'Rewrite it through the narrator’s perspective.',
    ],
  }),

  // Analytical coaching
  set({
    id: 'bank-eng-an-01',
    name: 'Stop Retelling the Plot',
    subject: 'English',
    years: '7–10',
    skill: 'Analytical writing',
    minutes: 10,
    prompts: [
      'Which sentence simply tells me what happened?',
      'What does this event reveal?',
      'Why has the author included it?',
      'What idea does it develop?',
      'Rewrite the point so it makes an argument rather than retelling.',
    ],
  }),
  set({
    id: 'bank-eng-an-02',
    name: 'Make a Real Analytical Claim',
    subject: 'English',
    years: '7–10',
    skill: 'Analytical writing',
    minutes: 10,
    prompts: [
      'What are you actually arguing?',
      'Could someone reasonably disagree with this?',
      'What does the text suggest, rather than simply show?',
      'Make the claim more specific.',
      'Make the claim answer the question.',
    ],
  }),
  set({
    id: 'bank-eng-an-03',
    name: 'Strong Topic Sentences',
    subject: 'English',
    years: '7–10',
    skill: 'Analytical writing',
    minutes: 10,
    prompts: [
      'What is this paragraph arguing?',
      'Which key word from the question should it address?',
      'Remove plot summary from the topic sentence.',
      'Make the sentence interpretive rather than descriptive.',
      'Does it clearly support your overall thesis?',
    ],
  }),
  set({
    id: 'bank-eng-an-04',
    name: 'Choose Better Evidence',
    subject: 'English',
    years: '7–10',
    skill: 'Analytical writing',
    minutes: 10,
    prompts: [
      'Which evidence best proves your point?',
      'Is the quote too long?',
      'Which word or phrase carries the strongest meaning?',
      'Could a more precise example work better?',
      'Why is this evidence stronger than another option?',
    ],
  }),
  set({
    id: 'bank-eng-an-05',
    name: 'Unpack the Quote',
    subject: 'English',
    years: '7–10',
    skill: 'Analytical writing',
    minutes: 10,
    prompts: [
      'Which word or phrase matters most?',
      'What does it suggest?',
      'What connotations does it carry?',
      'Why might the author have chosen it?',
      'How does it support your argument?',
    ],
  }),
  set({
    id: 'bank-eng-an-06',
    name: 'Authorial Choices',
    subject: 'English',
    years: '9–12',
    skill: 'Analytical writing',
    minutes: 12,
    prompts: [
      'What deliberate choice has the author made?',
      'Which aesthetic feature or literary device is being used?',
      'How does it shape meaning?',
      'Why is this choice effective here?',
      'How does it support your interpretation?',
    ],
  }),
  set({
    id: 'bank-eng-an-07',
    name: 'Audience Positioning',
    subject: 'English',
    years: '9–12',
    skill: 'Analytical writing',
    minutes: 10,
    prompts: [
      'How is the audience positioned to respond?',
      'What might the audience think, feel, question or believe?',
      'Which authorial choice creates this response?',
      'Why does this response matter?',
      'How does audience positioning support the author’s purpose?',
    ],
  }),
  set({
    id: 'bank-eng-an-08',
    name: 'Culture, Values & Beliefs',
    subject: 'English',
    years: '9–12',
    skill: 'Analytical writing',
    minutes: 12,
    prompts: [
      'What assumption, attitude, value or belief is represented here?',
      'Is the text reinforcing, questioning or challenging it?',
      'Which character, event or authorial choice reveals this?',
      'How might different audiences respond?',
      'How does this shape the text’s wider meaning?',
    ],
  }),
  set({
    id: 'bank-eng-an-09',
    name: 'Higher Insight',
    subject: 'English',
    years: '9–12',
    skill: 'Analytical writing',
    minutes: 10,
    prompts: [
      'What bigger idea does this reveal?',
      'What does this suggest about people, society, culture, identity, power, values or the wider issue?',
      'Why does this matter beyond this single moment?',
      'Is there a contradiction, tension or complexity here?',
      'How does this deepen your interpretation?',
    ],
  }),
  set({
    id: 'bank-eng-an-10',
    name: 'Link Evidence to Argument',
    subject: 'English',
    years: '7–10',
    skill: 'Analytical writing',
    minutes: 10,
    prompts: [
      'How does this evidence prove your point?',
      'What part of your argument does it strengthen?',
      'What key idea does it connect to?',
      'Rewrite the final sentence so it clearly returns to the argument.',
      'Does the paragraph still answer the question?',
    ],
  }),
  set({
    id: 'bank-eng-an-11',
    name: 'Extend & Synthesise',
    subject: 'English',
    years: '9–12',
    skill: 'Analytical writing',
    minutes: 12,
    prompts: [
      'What second piece of evidence could develop this idea?',
      'Does it reinforce, contrast or complicate the first example?',
      'What new layer does it add?',
      'Can you compare the two examples rather than discuss them separately?',
      'What stronger conclusion can you now draw?',
    ],
  }),
  set({
    id: 'bank-eng-teacher',
    name: 'TEACHER Analytical Paragraph',
    subject: 'English',
    years: '9–12',
    skill: 'Analytical writing',
    minutes: 15,
    note: 'Flagship exam scaffold: Topic, Evidence, Author+Audience, Culture, Higher insight, Extend, Return.',
    prompts: [
      {
        prompt: 'T — Topic / Thesis: What is your paragraph arguing?',
        helper: 'Write a clear point that answers the question.',
      },
      {
        prompt: 'E — Evidence: What evidence best proves your point?',
        helper: 'Use a precise quote, example or textual detail.',
      },
      {
        prompt: 'A — Author + Audience: What has the author done, and how does it position the audience?',
        helper: 'Analyse an aesthetic feature, literary device, language or structural choice, then explain what it makes the audience think, feel, notice or believe.',
      },
      {
        prompt: 'C — Culture: What assumptions, attitudes, values or beliefs are represented?',
        helper: 'Explain what the text reinforces, questions or challenges.',
      },
      {
        prompt: 'H — Human / Higher Insight: What bigger idea does this reveal?',
        helper: 'Think beyond the quote: people, society, culture, identity, power, values or the wider issue.',
      },
      {
        prompt: 'E — Extend: What further evidence develops or complicates your idea?',
        helper: 'Add a second example that strengthens, contrasts or deepens the analysis.',
      },
      {
        prompt: 'R — Return: How does this return to your argument?',
        helper: 'Tie the paragraph back to the question and your overall thesis.',
      },
    ],
  }),

  // Keep junior analytical scaffold (different year/purpose from TEACHER)
  set({
    id: 'bank-eng-05',
    name: 'Analytical Paragraph Builder',
    subject: 'English',
    years: '7–8',
    skill: 'Text analysis',
    minutes: 12,
    prompts: [
      {
        prompt: 'What claim are you making about the text?',
        helper: 'Not what happens — what it means.',
      },
      'Choose the evidence that best proves that claim.',
      'Zoom in on one important word, phrase or technique.',
      'What does it suggest that a casual reader might miss?',
      'What does the author want the reader to think or feel?',
      'Rewrite your final sentence so it returns to your claim.',
    ],
  }),

  // Literature / poetry / persuasive / essay
  set({
    id: 'bank-eng-08',
    name: 'Character Analysis',
    subject: 'English',
    years: '7–8',
    skill: 'Literature',
    minutes: 10,
    prompts: [
      'What do we learn about this character that is not said outright?',
      'Choose one moment that reveals this.',
      'What do they say, do, avoid or notice?',
      'Which detail carries the most weight?',
      'What does that detail suggest about them?',
      'Has our understanding of the character shifted by the end?',
    ],
  }),
  set({
    id: 'bank-eng-09',
    name: 'Theme Analysis',
    subject: 'English',
    years: '9–10',
    skill: 'Literature',
    minutes: 12,
    prompts: [
      'What important idea is the text exploring?',
      'Where is that idea under pressure or in conflict?',
      'Which character, event, image or technique develops it?',
      'How does the idea become more complex as the text unfolds?',
      'What might the author be pushing the audience to consider?',
      'How does this idea shape the text as a whole?',
    ],
  }),
  set({
    id: 'bank-eng-10',
    name: 'Poetry Close Reading',
    subject: 'English',
    years: '7–8',
    skill: 'Poetry',
    minutes: 10,
    prompts: [
      'What seems to be happening in this poem?',
      'Which word or image will not leave you alone?',
      'Name one technique doing real work.',
      'What feeling or idea does that choice create?',
      'Why might the poet have chosen it instead of something simpler?',
      'In one sentence: what is the poem saying?',
    ],
  }),
  set({
    id: 'bank-eng-11',
    name: 'Poetry Analysis',
    subject: 'English',
    years: '9–10',
    skill: 'Poetry',
    minutes: 12,
    prompts: [
      'What interpretation are you building?',
      'Which image, pattern or structural feature is doing the heavy lifting?',
      'What technique is being used?',
      'How does that choice shape tone or meaning?',
      'How does it position the reader?',
      'How does this feature connect to the poem’s bigger ideas?',
    ],
  }),
  set({
    id: 'bank-eng-12',
    name: 'Build a Persuasive Paragraph',
    subject: 'English',
    years: '7–8',
    skill: 'Persuasive writing',
    minutes: 10,
    prompts: [
      'What do you want your audience to believe or do?',
      'Give your strongest reason — not your safest one.',
      'Add evidence, an example or a concrete explanation.',
      'Choose one word or phrase for deliberate persuasive effect.',
      'Why should the audience care about this now?',
      'Finish by locking the argument shut.',
    ],
  }),
  set({
    id: 'bank-eng-13',
    name: 'Argument & Counterargument',
    subject: 'English',
    years: '9–10',
    skill: 'Persuasive writing',
    minutes: 12,
    prompts: [
      'State your main argument in one sentence.',
      'What evidence best supports it?',
      'What would a smart opponent say back?',
      'Why might that opposing view feel reasonable?',
      'How do you dismantle or limit that argument?',
      'How does addressing the other side make your case stronger?',
    ],
  }),
  set({
    id: 'bank-eng-14',
    name: 'Plan a Senior Essay',
    subject: 'English',
    years: '11–12',
    skill: 'Essay writing',
    minutes: 12,
    prompts: [
      {
        prompt: 'What is your overall contention?',
        helper: 'Make it arguable — someone could disagree.',
      },
      'What will each body paragraph argue?',
      'Which evidence will do the real work in each paragraph?',
      'How will the paragraphs build rather than repeat?',
      'What complexity, tension or alternative reading must you face?',
      'What should the reader understand by the final sentence?',
    ],
  }),

  // HASS — craft-level source & historical thinking
  set({
    id: 'bank-hass-15',
    name: 'Source Detective',
    subject: 'HASS',
    years: '5–6',
    skill: 'History',
    minutes: 10,
    note: 'Put one source on the board or in Inbox first.',
    prompts: [
      'What kind of source is this — and how can you tell?',
      'Who made it, and roughly when?',
      'What does it show or tell us in plain words?',
      'Why might someone have made this?',
      'What can this source help us learn?',
      'What can it not tell us?',
    ],
  }),
  set({
    id: 'bank-hass-16',
    name: 'Whose View Is Missing?',
    subject: 'HASS',
    years: '5–6',
    skill: 'History / Civics',
    minutes: 10,
    prompts: [
      'Who are the people or groups involved?',
      'What does each group want or believe?',
      'Why might their views clash?',
      'What evidence shows you that?',
      'Whose voice is missing from this story?',
      'Why does that missing view matter?',
    ],
  }),
  set({
    id: 'bank-hass-17',
    name: 'IOPCAM Source Analysis',
    subject: 'HASS',
    years: '7–8',
    skill: 'History',
    minutes: 12,
    note: 'Classic IOPCAM — sharpened for live use with one source visible.',
    prompts: [
      {
        prompt: 'I — Information: What does the source actually tell or show?',
        helper: 'Stick to what is there, not what you already know.',
      },
      'O — Origin: Who created it, and when?',
      'P — Purpose: Why was it created?',
      'C — Context: What was happening at the time that shaped it?',
      'A — Audience: Who was meant to see or hear this?',
      'M — Message: What main idea is it pushing?',
    ],
  }),
  set({
    id: 'bank-hass-18',
    name: 'Reliability & Usefulness',
    subject: 'HASS',
    years: '9–10',
    skill: 'History',
    minutes: 12,
    prompts: [
      'What claim or message does this source present?',
      'Who created it — and what skin do they have in the game?',
      'What was their purpose?',
      'What might distort their perspective?',
      {
        prompt: 'What makes this source useful for your inquiry?',
        helper: 'Useful for what question, exactly?',
      },
      'What are its limitations?',
      'What other evidence would you demand next?',
    ],
  }),
  set({
    id: 'bank-hass-19',
    name: 'Senior Source Evaluation',
    subject: 'HASS',
    years: '11–12',
    skill: 'History',
    minutes: 12,
    prompts: [
      'What perspective does this source construct?',
      'How do origin and context shape that perspective?',
      'How does purpose decide what is included or left out?',
      'Which detail inside the source is most historically significant?',
      'What limitation most weakens its usefulness?',
      'What evidence could corroborate — or wreck — this account?',
    ],
  }),
  set({
    id: 'bank-hass-20',
    name: 'Cause & Consequence',
    subject: 'HASS',
    years: '7–10',
    skill: 'History',
    minutes: 10,
    prompts: [
      'Name the event or change you are explaining.',
      'List the main causes — not just the dramatic one.',
      {
        prompt: 'Which cause was most significant?',
        helper: 'Significant means the outcome likely changes without it.',
      },
      'Prove that ranking in one sentence.',
      'What were the immediate consequences?',
      'What longer-term consequences still mattered?',
    ],
  }),
  set({
    id: 'bank-hass-21',
    name: 'Continuity & Change',
    subject: 'HASS',
    years: '7–10',
    skill: 'History',
    minutes: 10,
    prompts: [
      'What actually changed in this period?',
      'What stayed stubbornly the same?',
      'Who experienced the greatest change — and who barely felt it?',
      'What drove the change?',
      'Was the change sudden, staged or glacial?',
      'Why does that pattern of change matter historically?',
    ],
  }),
  set({
    id: 'bank-hass-22',
    name: 'Read the Map / Data',
    subject: 'HASS',
    years: '7–10',
    skill: 'Geography',
    minutes: 10,
    note: 'Works best with a map, graph or table on screen.',
    prompts: [
      'What does this map, graph or table actually show?',
      'What spatial or data pattern jumps out?',
      'Where is the pattern strongest — and weakest?',
      'What anomaly refuses to fit?',
      'Which geographic factors could explain the pattern?',
      'What conclusion can you defend with this evidence alone?',
    ],
  }),

  // Maths — thinking moves, not worksheets
  set({
    id: 'bank-maths-23',
    name: 'Understand Before You Solve',
    subject: 'Maths',
    years: '5–6',
    skill: 'Problem solving',
    minutes: 8,
    prompts: [
      'What is the problem asking you to find?',
      'Circle the information that actually helps.',
      'What operation or strategy might work — and why?',
      'Estimate before you calculate.',
      'Solve it.',
      'Does your answer make sense in the story of the problem?',
    ],
  }),
  set({
    id: 'bank-maths-24',
    name: 'Problem-Solving Routine',
    subject: 'Maths',
    years: '7–8',
    skill: 'Problem solving',
    minutes: 12,
    prompts: [
      'What is the unknown?',
      'What given information is useful?',
      'What information is a distraction?',
      {
        prompt: 'Choose a strategy and name it.',
        helper: 'Draw, table, equation, work backwards, simplify…',
      },
      'Show the working another student could follow.',
      'Check your answer a different way.',
      'Explain the solution in one clean sentence.',
    ],
  }),
  set({
    id: 'bank-maths-25',
    name: 'Complex Problem Attack',
    subject: 'Maths',
    years: '9–10',
    skill: 'Problem solving',
    minutes: 15,
    prompts: [
      'What quantities or variables are in play?',
      'What relationships link them?',
      'Which mathematical idea, formula or model fits?',
      'Break the problem into the smallest useful steps.',
      'Solve — and justify each key move.',
      'Does your result survive the original problem’s conditions?',
      'What assumptions or limitations should you flag?',
    ],
  }),
  set({
    id: 'bank-maths-26',
    name: 'Mathematical Modelling',
    subject: 'Maths',
    years: '11–12',
    skill: 'Senior mathematics',
    minutes: 18,
    prompts: [
      {
        prompt: 'Define the real-world problem in one sentence.',
        helper: 'What decision or prediction are you supporting?',
      },
      'What assumptions must you make — and which are risky?',
      'Identify the variables and relationships.',
      'Build a mathematical model that is simple enough to use.',
      'Solve the model.',
      'Interpret the result back in the original context.',
      'Is the answer reasonable for the real situation?',
      'Where does the model break down?',
    ],
  }),
  set({
    id: 'bank-maths-27',
    name: 'Find the Error',
    subject: 'Maths',
    years: '7–10',
    skill: 'Mathematical reasoning',
    minutes: 10,
    note: 'Put a worked example with an error on the board first.',
    prompts: [
      'Scan the working without calculating yet. Where does it feel wrong?',
      'Locate the first incorrect step.',
      'What was the student trying to do there?',
      'Why does that step fail?',
      'Write the correct step.',
      'Finish the solution from that point.',
    ],
  }),
  set({
    id: 'bank-maths-28',
    name: 'Explain Your Method',
    subject: 'Maths',
    years: '7–10',
    skill: 'Mathematical reasoning',
    minutes: 10,
    prompts: [
      'Name the strategy you used.',
      'Why that strategy — not another?',
      'Show only the steps that earn the answer.',
      'Which step demanded the most thinking?',
      'How did you check?',
      'Explain so a classmate who was stuck could restart from your words.',
    ],
  }),
  set({
    id: 'bank-maths-29',
    name: 'Compare Two Strategies',
    subject: 'Maths',
    years: '7–10',
    skill: 'Mathematical reasoning',
    minutes: 10,
    note: 'Show Strategy A and B on the board, or have two student methods ready.',
    prompts: [
      'How does Strategy A actually work?',
      'How does Strategy B work?',
      'What do they share underneath?',
      'Where do they diverge?',
      'Which is more efficient for this problem — and why?',
      'When would the other strategy be the smarter choice?',
    ],
  }),
  set({
    id: 'bank-maths-30',
    name: 'Interrogate the Data',
    subject: 'Maths',
    years: '7–10',
    skill: 'Data',
    minutes: 10,
    note: 'Needs a graph or table visible.',
    prompts: [
      'What does this graph or table claim to represent?',
      'What pattern do you see — not what you expected to see?',
      'What comparison is most revealing?',
      'What looks unusual or suspicious?',
      'What calculation would unlock the story?',
      'What conclusion can you defend — and what can you not?',
    ],
  }),

  // Science — investigation & explanation craft
  set({
    id: 'bank-sci-31',
    name: 'Predict–Observe–Explain',
    subject: 'Science',
    years: '5–8',
    skill: 'Scientific thinking',
    minutes: 10,
    note: 'Pause between predict / observe / explain during the demo.',
    prompts: [
      'What do you predict will happen?',
      'Why — using science, not vibes?',
      'What actually happened?',
      'Was your prediction supported, partial or wrong?',
      'What scientific idea best explains the result?',
    ],
  }),
  set({
    id: 'bank-sci-32',
    name: 'Nail the Variables',
    subject: 'Science',
    years: '7–8',
    skill: 'Investigations',
    minutes: 8,
    prompts: [
      'Write the investigation question in one line.',
      'What will you deliberately change?',
      'What will you measure?',
      'What must stay the same?',
      'Why would changing those “same” things wreck the test?',
      'How will you make this a fair test?',
    ],
  }),
  set({
    id: 'bank-sci-33',
    name: 'Plan an Investigation',
    subject: 'Science',
    years: '7–8',
    skill: 'Investigations',
    minutes: 12,
    prompts: [
      'What question are you actually testing?',
      {
        prompt: 'State a testable hypothesis.',
        helper: 'If… then… because…',
      },
      'Independent variable: what you change.',
      'Dependent variable: what you measure.',
      'Controlled variables: what you keep constant.',
      'What equipment do you need — and why each item?',
      'What data will convince you the hypothesis is supported or not?',
    ],
  }),
  set({
    id: 'bank-sci-34',
    name: 'Claim–Evidence–Reasoning',
    subject: 'Science',
    years: '9–10',
    skill: 'Scientific explanation',
    minutes: 10,
    prompts: [
      {
        prompt: 'C — Claim: What are you asserting?',
        helper: 'One clear sentence. No waffle.',
      },
      'E — Evidence: Which data or observation supports it?',
      'R — Reasoning: Which scientific concept links evidence to claim?',
      'How exactly does the evidence force that claim?',
      'What evidence does not fit — and what do you do with it?',
      'Write a conclusion a skeptic could still respect.',
    ],
  }),
  set({
    id: 'bank-sci-35',
    name: 'Read the Results',
    subject: 'Science',
    years: '7–10',
    skill: 'Data analysis',
    minutes: 10,
    note: 'Needs results, a graph or a table in view.',
    prompts: [
      'What trend or pattern is actually there?',
      'Which piece of evidence most strongly supports that reading?',
      'What looks like an outlier or mess?',
      'How strong is the pattern — tight, soft or wishful?',
      'What scientific explanation could account for it?',
      'What conclusion is fair — and what would be overclaiming?',
    ],
  }),
  set({
    id: 'bank-sci-36',
    name: 'Evaluate the Method',
    subject: 'Science',
    years: '9–10',
    skill: 'Investigations',
    minutes: 12,
    prompts: [
      'How reliable are these results?',
      'Which results look inconsistent — and why might that be?',
      'Name the most likely sources of error.',
      'Was the method actually suited to the question?',
      'What one change would improve the investigation most?',
      'What further test would make the conclusion harder to dismiss?',
    ],
  }),
  set({
    id: 'bank-sci-37',
    name: 'Build a Scientific Explanation',
    subject: 'Science',
    years: '7–10',
    skill: 'Scientific writing',
    minutes: 10,
    prompts: [
      'What phenomenon are you explaining?',
      'Which scientific ideas must appear in a good explanation?',
      'What evidence or example will you lean on?',
      'Connect the evidence to the science — show the chain.',
      'Replace one everyday word with precise scientific language.',
      'Finish: why does this happen?',
    ],
  }),
  set({
    id: 'bank-sci-38',
    name: 'Evaluate Scientific Evidence',
    subject: 'Science',
    years: '11–12',
    skill: 'Senior science',
    minutes: 15,
    prompts: [
      'What claim or conclusion is on the table?',
      'What evidence is offered for it?',
      {
        prompt: 'How reliable is that evidence?',
        helper: 'Sample, method, bias, reproducibility…',
      },
      'Where is the uncertainty, error or limitation?',
      'How valid is the leap from evidence to conclusion?',
      'What alternative explanations survive?',
      'What additional evidence would tip you one way or the other?',
    ],
  }),

  // General — tomorrow’s lesson glue
  set({
    id: 'bank-gen-39',
    name: 'Retrieval Warm-Up',
    subject: 'General',
    years: 'All',
    skill: 'Lesson opener',
    minutes: 8,
    prompts: [
      'Without looking: what stuck from last lesson?',
      'Write three important ideas — not three titles.',
      'Give one concrete example.',
      'Which idea are you least certain about?',
      'Write the one question you still need answered.',
    ],
  }),
  set({
    id: 'bank-gen-40',
    name: 'Confidence Pulse',
    subject: 'General',
    years: 'All',
    skill: 'Formative check',
    minutes: 5,
    prompts: [
      'Confidence right now: 1–5. Be honest.',
      'What part feels under control?',
      'Where are you wobbly?',
      'What single thing would lift you one point?',
    ],
  }),
  set({
    id: 'bank-gen-41',
    name: 'Kill the Misconception',
    subject: 'General',
    years: 'All',
    skill: 'Understanding check',
    minutes: 8,
    note: 'Put a tempting wrong statement or example on the board.',
    prompts: [
      'Read it carefully. What smells wrong?',
      'Name the incorrect idea.',
      'Why is it wrong?',
      'State the correct idea cleanly.',
      'What trap would make a student fall for the misconception?',
    ],
  }),
  set({
    id: 'bank-gen-42',
    name: 'Exit Ticket That Matters',
    subject: 'General',
    years: 'All',
    skill: 'Lesson close',
    minutes: 6,
    prompts: [
      'What is the one idea from today you must not forget?',
      'Explain it in your own words — no copying the slide.',
      'Give an example from today’s work.',
      'What can you do now that you could not do at the start?',
      'What are you still unsure about?',
    ],
  }),
  set({
    id: 'bank-gen-43',
    name: 'Peer Feedback That Helps',
    subject: 'General',
    years: '7–12',
    skill: 'Feedback',
    minutes: 8,
    note: 'Students need a peer’s work visible.',
    prompts: [
      'What is working well — point to a specific line or move?',
      'Quote or describe that strength.',
      'Where does meaning go foggy?',
      'Ask the writer one sharp question.',
      'Give one change they could make in the next five minutes.',
    ],
  }),
  set({
    id: 'bank-gen-44',
    name: 'Use the Feedback',
    subject: 'General',
    years: '7–12',
    skill: 'Writing & feedback',
    minutes: 12,
    note: 'Perfect after Inbox notes or board comments.',
    prompts: [
      'Which section are you improving?',
      'Read the teacher comment again. What is it actually asking?',
      'In your words: what must change?',
      'Describe the revision you will make before you make it.',
      'Make the change.',
      'How is the work stronger now?',
    ],
  }),
  set({
    id: 'bank-gen-45',
    name: 'Own the Key Word',
    subject: 'General',
    years: '5–10',
    skill: 'Vocabulary',
    minutes: 8,
    note: 'Put the target word on the board.',
    prompts: [
      'What do you think this word means in this subject?',
      'Say it in plain words a Year 5 student would get.',
      'Use it in a sentence about today’s work.',
      'Name a near-synonym — and how it differs.',
      'Give a clear example.',
      'What do people often think it means that it does not?',
    ],
  }),
  set({
    id: 'bank-gen-46',
    name: 'Compare to Decide',
    subject: 'General',
    years: '5–10',
    skill: 'Thinking routine',
    minutes: 8,
    prompts: [
      'What do these two things share?',
      'Name one difference that actually matters.',
      'Find a second difference.',
      'Which difference changes your judgment most?',
      'Why that one?',
      'What conclusion does the comparison force?',
    ],
  }),
  set({
    id: 'bank-gen-47',
    name: 'Live Work Check-In',
    subject: 'General',
    years: 'All',
    skill: 'Live monitoring',
    minutes: 5,
    note: 'Fire mid-task when you need eyes on the room fast.',
    prompts: [
      'What are you doing right now — in one sentence?',
      'What have you finished?',
      'What is next?',
      'Where are you stuck, if anywhere?',
      'If stuck: name the exact step that broke.',
      'What do you need from your teacher in the next two minutes?',
    ],
  }),
  set({
    id: 'bank-gen-48',
    name: 'Teach It Back',
    subject: 'General',
    years: 'All',
    skill: 'Understanding',
    minutes: 8,
    prompts: [
      'Explain today’s idea to someone who missed the lesson.',
      'What must they understand first?',
      'Give the example that makes it click.',
      'What mistake should they avoid?',
      'What question would prove they got it?',
    ],
  }),
];

const YEAR_ORDER = ['5–6', '7–8', '9–10', '11–12'];

function expandYears(label) {
  const raw = String(label || '').replace(/-/g, '–').trim();
  if (!raw || raw === 'All') return new Set(YEAR_ORDER);
  if (YEAR_ORDER.includes(raw)) return new Set([raw]);
  const match = raw.match(/^(\d+)–(\d+)$/);
  if (!match) return new Set(YEAR_ORDER);
  const start = Number(match[1]);
  const end = Number(match[2]);
  const covered = new Set();
  for (const band of YEAR_ORDER) {
    const [a, b] = band.split('–').map(Number);
    if (a <= end && b >= start) covered.add(band);
  }
  return covered.size ? covered : new Set(YEAR_ORDER);
}

export function setMatchesFilters(set, subject, yearBand) {
  if (subject && subject !== 'All' && set.subject !== subject) return false;
  if (!yearBand || yearBand === 'All') return true;
  return expandYears(set.years).has(yearBand);
}

export function formatSetMeta(set) {
  const years = set.years === 'All' ? 'All years' : `Years ${set.years}`;
  const mins = set.minutes ? `~${set.minutes} min` : '';
  return [set.subject, years, set.skill, mins].filter(Boolean).join(' · ');
}
