/** Launch library of teaching question sets. Bank sets are not deletable. */

function q(prompts) {
  return prompts.map((prompt, index) => ({
    id: `p${index + 1}`,
    type: 'short',
    prompt,
    options: [],
    correctAnswer: '',
  }));
}

function set(def) {
  return {
    ...def,
    bank: true,
    questions: q(def.prompts),
  };
}

export const SUBJECTS = ['English', 'HASS', 'Maths', 'Science', 'General'];
export const YEAR_BANDS = ['5–6', '7–8', '9–10', '11–12'];

export const QUESTION_SET_BANK = [
  // English core — 14
  set({
    id: 'bank-eng-01',
    name: 'Build a Strong Paragraph',
    subject: 'English',
    years: '5–6',
    skill: 'Writing',
    minutes: 10,
    prompts: [
      'What is the main idea of your paragraph?',
      'Write a sentence that clearly introduces that idea.',
      'Add an example, fact or detail.',
      'Explain how your example supports your main idea.',
      'Write a final sentence that wraps up the paragraph.',
      'Reread it. Which sentence could you make clearer?',
    ],
  }),
  set({
    id: 'bank-eng-02',
    name: 'Build a Narrative Paragraph',
    subject: 'English',
    years: '5–6',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'Where is your character?',
      'What is happening right now?',
      'Add something your character can see, hear or feel.',
      'What does your character do?',
      'What happens next?',
      'Reread your paragraph. Add or improve one detail.',
    ],
  }),
  set({
    id: 'bank-eng-03',
    name: 'Bring a Scene to Life',
    subject: 'English',
    years: '7–8',
    skill: 'Creative writing',
    minutes: 10,
    prompts: [
      'What does your character want in this moment?',
      'What is happening around them?',
      'Add one sensory detail that helps the reader picture the scene.',
      'Show how your character feels without simply naming the feeling.',
      'Use an action, thought or line of dialogue to reveal something about the character.',
      'Revise one sentence to make the scene more vivid.',
    ],
  }),
  set({
    id: 'bank-eng-04',
    name: 'Craft a Powerful Scene',
    subject: 'English',
    years: '9–10',
    skill: 'Creative writing',
    minutes: 12,
    prompts: [
      'What tension, conflict or idea should this scene develop?',
      'What should the reader notice first?',
      'Choose an action, image or piece of dialogue that reveals character.',
      'Add a detail with emotional or symbolic significance.',
      'How will you control pace in this moment?',
      'Revise one sentence for greater precision or impact.',
    ],
  }),
  set({
    id: 'bank-eng-05',
    name: 'Analytical Paragraph Builder',
    subject: 'English',
    years: '7–8',
    skill: 'Text analysis',
    minutes: 12,
    prompts: [
      'What is your main point about the text?',
      'Choose evidence that supports your point.',
      'Which important word, phrase or technique can you zoom in on?',
      'What does it suggest?',
      'What does the author want the reader to think or feel?',
      'Connect your analysis back to your main point.',
    ],
  }),
  set({
    id: 'bank-eng-06',
    name: 'Develop an Analytical Paragraph',
    subject: 'English',
    years: '9–10',
    skill: 'Text analysis',
    minutes: 15,
    prompts: [
      'What argument will this paragraph make?',
      'Select the strongest evidence for that argument.',
      'Identify an important language, structural or stylistic choice.',
      'Explain how that choice shapes meaning.',
      'How does it influence the audience?',
      'How does this evidence strengthen your overall interpretation?',
    ],
  }),
  set({
    id: 'bank-eng-07',
    name: 'Senior Analytical Paragraph',
    subject: 'English',
    years: '11–12',
    skill: 'Text analysis',
    minutes: 15,
    prompts: [
      'What interpretation are you advancing?',
      'Which textual evidence best supports it?',
      'Analyse a deliberate language, structural or stylistic choice.',
      'How does this choice position the audience?',
      'How do context, perspective or purpose deepen the meaning?',
      'Connect the analysis to the broader argument of your essay.',
    ],
  }),
  set({
    id: 'bank-eng-08',
    name: 'Character Analysis',
    subject: 'English',
    years: '7–8',
    skill: 'Literature',
    minutes: 10,
    prompts: [
      'What do we learn about this character?',
      'Choose a moment that reveals this.',
      'What does the character say, do or think?',
      'Which detail is particularly important?',
      'What does this suggest about the character?',
      'Does our understanding of the character change?',
    ],
  }),
  set({
    id: 'bank-eng-09',
    name: 'Theme Analysis',
    subject: 'English',
    years: '9–10',
    skill: 'Literature',
    minutes: 12,
    prompts: [
      'What important idea is the text exploring?',
      'Where can you see this idea in the text?',
      'Which character, event, image or technique helps develop it?',
      'How does the idea change or become more complex?',
      'What might the author be encouraging the audience to consider?',
      'How does this idea connect to the text as a whole?',
    ],
  }),
  set({
    id: 'bank-eng-10',
    name: 'Poetry Close Reading',
    subject: 'English',
    years: '7–8',
    skill: 'Poetry',
    minutes: 10,
    prompts: [
      'What seems to be happening in the poem?',
      'Which word or image stands out to you?',
      'What technique can you identify?',
      'What feeling or idea does it create?',
      'Why might the poet have chosen it?',
      'What do you think the poem is saying overall?',
    ],
  }),
  set({
    id: 'bank-eng-11',
    name: 'Poetry Analysis',
    subject: 'English',
    years: '9–10',
    skill: 'Poetry',
    minutes: 12,
    prompts: [
      'What interpretation of the poem are you developing?',
      'Which image, word pattern or structural feature is significant?',
      'What technique is being used?',
      'How does this choice shape tone or meaning?',
      'How does it influence the reader?',
      "How does this feature connect to the poem's broader ideas?",
    ],
  }),
  set({
    id: 'bank-eng-12',
    name: 'Build a Persuasive Paragraph',
    subject: 'English',
    years: '7–8',
    skill: 'Persuasive writing',
    minutes: 10,
    prompts: [
      'What do you want your audience to believe?',
      'Give your strongest reason.',
      'Add evidence, an example or an explanation.',
      'Choose persuasive language deliberately.',
      'Explain why this issue matters.',
      'Finish by reinforcing your argument.',
    ],
  }),
  set({
    id: 'bank-eng-13',
    name: 'Argument & Counterargument',
    subject: 'English',
    years: '9–10',
    skill: 'Persuasive writing',
    minutes: 12,
    prompts: [
      'What is your main argument?',
      'What evidence supports it?',
      'What might someone who disagrees say?',
      'Why might they hold that view?',
      'How could you respond to that argument?',
      'How does addressing the opposing view strengthen your position?',
    ],
  }),
  set({
    id: 'bank-eng-14',
    name: 'Plan a Senior Essay',
    subject: 'English',
    years: '11–12',
    skill: 'Essay writing',
    minutes: 12,
    prompts: [
      'What is your overall contention or interpretation?',
      'What will each body paragraph argue?',
      'Which evidence will best support each argument?',
      'How will the paragraphs build on one another?',
      'What complexity, tension or alternative interpretation should you address?',
      'What should the reader understand by the end of the essay?',
    ],
  }),

  // English coaching — Creative writing
  set({
    id: 'bank-eng-cw-01',
    name: "Show, Don't Tell",
    subject: 'English',
    years: '7–8',
    skill: 'Creative coaching',
    minutes: 8,
    note: 'Use when a draft names feelings instead of showing them.',
    prompts: [
      'Find a sentence that tells the reader how the character feels.',
      'Remove the emotion word.',
      'What could the character do physically instead?',
      'Add one small body-language or sensory detail.',
      'Reread it. Can the reader now infer the feeling without being told?',
    ],
  }),
  set({
    id: 'bank-eng-cw-02',
    name: 'Cut the Emotional Explanation',
    subject: 'English',
    years: '9–12',
    skill: 'Creative coaching',
    minutes: 8,
    note: 'For mature drafts that explain emotions after already showing them.',
    prompts: [
      'Find a sentence that explains an emotion the scene has already shown.',
      'What has the character already done, noticed or said that reveals it?',
      'Delete or reduce the explanation.',
      'Could one image, gesture or contradiction carry the meaning instead?',
      'Trust the reader. What can you leave unsaid?',
    ],
  }),
  set({
    id: 'bank-eng-cw-03',
    name: 'Make the Setting Work',
    subject: 'English',
    years: '7–10',
    skill: 'Creative coaching',
    minutes: 8,
    prompts: [
      'What should the setting make the reader feel in this moment?',
      'Replace one general description with a precise detail.',
      'Add one sound, texture, smell or temperature detail.',
      'How can the character interact with the setting instead of simply observing it?',
      'Which detail could reinforce the mood, tension or idea of the scene?',
    ],
  }),
  set({
    id: 'bank-eng-cw-04',
    name: 'Character Through Action',
    subject: 'English',
    years: '7–10',
    skill: 'Creative coaching',
    minutes: 8,
    prompts: [
      'What does your character want right now?',
      'Which action could reveal that want without explaining it?',
      'Add one gesture, habit or choice that tells us something about the character.',
      'Find one sentence that explains the character. Could the action do that work instead?',
      'What should the reader infer about the character from this moment?',
    ],
  }),
  set({
    id: 'bank-eng-cw-05',
    name: 'Dialogue With Purpose',
    subject: 'English',
    years: '7–10',
    skill: 'Creative coaching',
    minutes: 8,
    prompts: [
      'What does each character want from this conversation?',
      'Cut one greeting, filler line or piece of information both characters already know.',
      'What is one thing a character is thinking but will not say directly?',
      'Add an action or reaction that creates subtext.',
      'Do the characters sound different from each other? Change one line if they do not.',
    ],
  }),
  set({
    id: 'bank-eng-cw-06',
    name: 'Build Tension',
    subject: 'English',
    years: '7–10',
    skill: 'Creative coaching',
    minutes: 9,
    prompts: [
      'What does the character want in this moment?',
      'What is preventing them from getting it?',
      'Where could you delay the answer, action or reveal?',
      'What information could you withhold from the reader for a little longer?',
      'Add one small detail that signals something is wrong.',
      'End the section with pressure still unresolved.',
    ],
  }),
  set({
    id: 'bank-eng-cw-07',
    name: 'Control the Pace',
    subject: 'English',
    years: '9–12',
    skill: 'Creative coaching',
    minutes: 9,
    prompts: [
      'Which moment deserves the most attention?',
      'Slow that moment using action, sensory detail or thought.',
      'Which less important part can you compress or skip?',
      'Where could a short sentence create impact?',
      'Where could a paragraph break control the reader’s pace?',
      'Reread the section. Does the pace match the importance of each moment?',
    ],
  }),
  set({
    id: 'bank-eng-cw-08',
    name: 'Fix the Opening',
    subject: 'English',
    years: '7–10',
    skill: 'Creative coaching',
    minutes: 8,
    prompts: [
      'How late can you enter the scene and still make sense?',
      'Can you begin with an action, image, voice or problem rather than background information?',
      'What backstory can wait until later?',
      'What question or tension should the opening create?',
      'Rewrite the first sentence so it earns the second one.',
    ],
  }),
  set({
    id: 'bank-eng-cw-09',
    name: 'Fix the Ending',
    subject: 'English',
    years: '7–10',
    skill: 'Creative coaching',
    minutes: 8,
    prompts: [
      'What has changed by the end of this scene or story?',
      'Find any sentence that explains the meaning too directly.',
      'Could an image, action, line of dialogue or echo from earlier carry that meaning instead?',
      'What do you want the reader to feel or wonder after the final line?',
      'Try cutting the last explanatory sentence. Is the ending stronger without it?',
    ],
  }),
  set({
    id: 'bank-eng-cw-10',
    name: 'Sentence Craft & Precision',
    subject: 'English',
    years: '9–12',
    skill: 'Creative coaching',
    minutes: 10,
    prompts: [
      'Find one weak or general verb. Replace it with a more precise one.',
      'Find one vague noun or description. Make it specific.',
      'Find a sentence that begins predictably. Change the opening.',
      'Find a sentence carrying too many ideas. Split or reshape it.',
      'Remove words that add length but not meaning.',
      'Read the paragraph aloud. Where could the rhythm be sharper?',
    ],
  }),

  // English coaching — Analytical writing
  set({
    id: 'bank-eng-an-01',
    name: 'Stop Retelling the Plot',
    subject: 'English',
    years: '7–8',
    skill: 'Analytical coaching',
    minutes: 8,
    note: 'Use when a paragraph tells what happened instead of explaining what it means.',
    prompts: [
      'Find the sentence that mainly tells me what happened.',
      'What does that moment reveal about the character, idea or conflict?',
      'Why might the author have included this moment?',
      'Turn the plot detail into a point about the text.',
      'Use the event as evidence, then explain what it shows.',
    ],
  }),
  set({
    id: 'bank-eng-an-02',
    name: 'Turn Summary Into Analysis',
    subject: 'English',
    years: '9–10',
    skill: 'Analytical coaching',
    minutes: 8,
    prompts: [
      'Which sentence is summarising the text rather than analysing it?',
      'Ask: so what does this actually reveal?',
      'What deliberate choice has the author made here?',
      'How does that choice shape meaning or the audience response?',
      'Rewrite the sentence so it makes an interpretation, not a summary.',
    ],
  }),
  set({
    id: 'bank-eng-an-03',
    name: 'Fix the Topic Sentence',
    subject: 'English',
    years: '7–8',
    skill: 'Analytical coaching',
    minutes: 7,
    prompts: [
      'What is the one main point this paragraph is trying to prove?',
      'Does your topic sentence make a point, or just mention an event or character?',
      'Which key idea from the question should appear in the sentence?',
      'What does the author suggest about that idea?',
      'Rewrite the topic sentence as a clear claim about the text.',
    ],
  }),
  set({
    id: 'bank-eng-an-04',
    name: 'Make a Real Analytical Claim',
    subject: 'English',
    years: '9–12',
    skill: 'Analytical coaching',
    minutes: 8,
    prompts: [
      'What claim is this paragraph making that someone could actually discuss or challenge?',
      'Remove any plot summary or obvious fact from the topic sentence.',
      'Which concept, value, tension or idea is really being examined?',
      'Can you make the claim more precise by adding a qualification or tension?',
      'How does this claim contribute to your overall thesis or interpretation?',
    ],
  }),
  set({
    id: 'bank-eng-an-05',
    name: 'Choose Better Evidence',
    subject: 'English',
    years: '7–10',
    skill: 'Analytical coaching',
    minutes: 8,
    prompts: [
      'State the point you are trying to prove before looking at the quote.',
      'Which piece of evidence proves that point most directly?',
      'What is the shortest part of the evidence you actually need?',
      'Which word or detail gives you the most to analyse?',
      'Remove any quoted material you are not going to explain.',
    ],
  }),
  set({
    id: 'bank-eng-an-06',
    name: 'Unpack the Quote',
    subject: 'English',
    years: '7–8',
    skill: 'Analytical coaching',
    minutes: 8,
    prompts: [
      'Which word or short phrase in your evidence matters most?',
      'What does that word suggest?',
      'What feeling, idea or association does it create?',
      'Is there a technique or pattern worth naming?',
      'Explain how this detail supports your main point.',
    ],
  }),
  set({
    id: 'bank-eng-an-07',
    name: 'Zoom In on Language',
    subject: 'English',
    years: '9–10',
    skill: 'Analytical coaching',
    minutes: 9,
    prompts: [
      'Which single word, image, contrast or pattern is most significant?',
      'What connotations or associations does it carry?',
      'Why is that particular choice more effective than a neutral alternative?',
      'How does the choice shape tone, characterisation or meaning?',
      'Connect that close analysis to your broader interpretation.',
    ],
  }),
  set({
    id: 'bank-eng-an-08',
    name: 'Explain the Effect',
    subject: 'English',
    years: '7–10',
    skill: 'Analytical coaching',
    minutes: 8,
    prompts: [
      'You have named the technique. What does it actually create?',
      'What specific idea, feeling or impression does the audience receive?',
      'How does the author position the audience to view the character, event or idea?',
      'Why might the author want that response?',
      'Link the effect back to the point of the paragraph.',
    ],
  }),
  set({
    id: 'bank-eng-an-09',
    name: 'Link Evidence to the Argument',
    subject: 'English',
    years: '9–12',
    skill: 'Analytical coaching',
    minutes: 8,
    prompts: [
      'What does this evidence prove?',
      'Which part of your paragraph claim does it support?',
      'Have you explained the connection, or are you expecting the quote to speak for itself?',
      'Write one sentence that makes the reasoning explicit.',
      'How does this point strengthen the overall argument of the essay?',
    ],
  }),
  set({
    id: 'bank-eng-an-10',
    name: 'Deepen the Interpretation',
    subject: 'English',
    years: '11–12',
    skill: 'Analytical coaching',
    minutes: 10,
    prompts: [
      'What is the most obvious reading of this moment or idea?',
      'What complicates that reading?',
      'Is there a tension, contradiction or alternative interpretation you could consider?',
      'How might context, perspective or purpose change the way we understand it?',
      'What larger idea does this complexity reveal?',
      'Revise your analysis so it shows nuance rather than certainty where appropriate.',
    ],
  }),

  // HASS — 8
  set({
    id: 'bank-hass-15',
    name: 'Source Detective',
    subject: 'HASS',
    years: '5–6',
    skill: 'History',
    minutes: 10,
    prompts: [
      'What kind of source is this?',
      'Who created it?',
      'When was it created?',
      'What does it show or tell us?',
      'Why might it have been created?',
      'What can this source help us learn?',
    ],
  }),
  set({
    id: 'bank-hass-16',
    name: 'Different Views of an Event',
    subject: 'HASS',
    years: '5–6',
    skill: 'History / Civics',
    minutes: 10,
    prompts: [
      'Who are the people or groups involved?',
      'What does each person or group think?',
      'Why might their views be different?',
      'What evidence tells you this?',
      'Whose point of view might be missing?',
      'Why is it useful to consider more than one point of view?',
    ],
  }),
  set({
    id: 'bank-hass-17',
    name: 'IOPCAM Source Analysis',
    subject: 'HASS',
    years: '7–8',
    skill: 'History',
    minutes: 12,
    prompts: [
      'Information: What does the source tell or show us?',
      'Origin: Who created it, and when?',
      'Purpose: Why was it created?',
      'Context: What was happening at the time?',
      'Audience: Who was it created for?',
      'Message: What main idea or message is being communicated?',
    ],
  }),
  set({
    id: 'bank-hass-18',
    name: 'Reliability & Usefulness',
    subject: 'HASS',
    years: '9–10',
    skill: 'History',
    minutes: 12,
    prompts: [
      'What claim or message does the source present?',
      'Who created it?',
      'What was their purpose?',
      'What might influence their perspective?',
      'What makes the source useful?',
      'What are its limitations?',
      'What other evidence would help you check it?',
    ],
  }),
  set({
    id: 'bank-hass-19',
    name: 'Senior Source Evaluation',
    subject: 'HASS',
    years: '11–12',
    skill: 'History',
    minutes: 12,
    prompts: [
      'What perspective does the source construct?',
      'How do its origin and context shape that perspective?',
      'How does purpose influence what is included or omitted?',
      'Which evidence within the source is most significant?',
      'What limitations affect its usefulness?',
      'What evidence could corroborate or challenge it?',
    ],
  }),
  set({
    id: 'bank-hass-20',
    name: 'Cause & Consequence',
    subject: 'HASS',
    years: '7–10',
    skill: 'History',
    minutes: 10,
    prompts: [
      'What event or change are you examining?',
      'What were the main causes?',
      'Which cause was most significant?',
      'Why?',
      'What were the immediate consequences?',
      'What were the longer-term consequences?',
    ],
  }),
  set({
    id: 'bank-hass-21',
    name: 'Continuity & Change',
    subject: 'HASS',
    years: '7–10',
    skill: 'History',
    minutes: 10,
    prompts: [
      'What changed during this period?',
      'What stayed the same?',
      'Who experienced the greatest change?',
      'What caused the change?',
      'Was the change sudden or gradual?',
      'Why was the change significant?',
    ],
  }),
  set({
    id: 'bank-hass-22',
    name: 'Interpret Geographic Data',
    subject: 'HASS',
    years: '7–10',
    skill: 'Geography',
    minutes: 10,
    prompts: [
      'What does the map, graph or data show?',
      'What spatial pattern can you identify?',
      'Where is the pattern strongest or weakest?',
      'Is anything unusual?',
      'What geographic factors might explain the pattern?',
      'What conclusion is supported by the evidence?',
    ],
  }),

  // Maths — 8
  set({
    id: 'bank-maths-23',
    name: 'Understand the Problem',
    subject: 'Maths',
    years: '5–6',
    skill: 'Problem solving',
    minutes: 8,
    prompts: [
      'What is the problem asking you to find?',
      'Which information will help you solve it?',
      'What operation or strategy might work?',
      'Estimate what you think the answer might be.',
      'Solve the problem.',
      'Does your answer make sense?',
    ],
  }),
  set({
    id: 'bank-maths-24',
    name: 'Problem-Solving Routine',
    subject: 'Maths',
    years: '7–8',
    skill: 'Problem solving',
    minutes: 12,
    prompts: [
      'What is the unknown?',
      'What useful information have you been given?',
      'Is any information unnecessary?',
      'Choose a strategy.',
      'Show your working clearly.',
      'Check your answer.',
      'Explain your solution in one sentence.',
    ],
  }),
  set({
    id: 'bank-maths-25',
    name: 'Complex Problem Solving',
    subject: 'Maths',
    years: '9–10',
    skill: 'Problem solving',
    minutes: 15,
    prompts: [
      'What quantities or variables are involved?',
      'What relationships can you identify?',
      'Which mathematical idea, formula or strategy applies?',
      'Break the problem into logical steps.',
      'Solve and justify your method.',
      'Check your result against the original problem.',
      'Are there any limitations or assumptions?',
    ],
  }),
  set({
    id: 'bank-maths-26',
    name: 'Mathematical Modelling',
    subject: 'Maths',
    years: '11–12',
    skill: 'Senior mathematics',
    minutes: 18,
    prompts: [
      'Define the problem clearly.',
      'What assumptions will you need to make?',
      'Identify the variables and relationships involved.',
      'Develop an appropriate mathematical model.',
      'Solve the model.',
      'Interpret your result in the original context.',
      'Test whether the solution is reasonable.',
      'Evaluate the limitations of the model.',
    ],
  }),
  set({
    id: 'bank-maths-27',
    name: 'Find the Error',
    subject: 'Maths',
    years: '7–10',
    skill: 'Mathematical reasoning',
    minutes: 10,
    note: 'Works best with a worked example on the board.',
    prompts: [
      'Study the working carefully.',
      'Where does the first error occur?',
      'What do you think the student was trying to do?',
      'Why is that step incorrect?',
      'Show the correct step.',
      'Continue the solution from there.',
    ],
  }),
  set({
    id: 'bank-maths-28',
    name: 'Explain Your Method',
    subject: 'Maths',
    years: '7–10',
    skill: 'Mathematical reasoning',
    minutes: 10,
    prompts: [
      'What strategy did you use?',
      'Why did you choose it?',
      'Show the important steps.',
      'Which step required the most thinking?',
      'How did you check your answer?',
      'Explain your method so another student could follow it.',
    ],
  }),
  set({
    id: 'bank-maths-29',
    name: 'Compare Two Strategies',
    subject: 'Maths',
    years: '7–10',
    skill: 'Mathematical reasoning',
    minutes: 10,
    prompts: [
      'How does Strategy A work?',
      'How does Strategy B work?',
      'What do the strategies have in common?',
      'How are they different?',
      'Which is more efficient for this problem?',
      'When might the other strategy be more useful?',
    ],
  }),
  set({
    id: 'bank-maths-30',
    name: 'Read the Data',
    subject: 'Maths',
    years: '7–10',
    skill: 'Data',
    minutes: 10,
    prompts: [
      'What does the graph or table represent?',
      'What pattern can you see?',
      'What comparison can you make?',
      'Is there anything unusual?',
      'What calculation could help you understand the data?',
      'What conclusion is supported by the data?',
    ],
  }),

  // Science — 8
  set({
    id: 'bank-sci-31',
    name: 'Predict–Observe–Explain',
    subject: 'Science',
    years: '5–8',
    skill: 'Scientific thinking',
    minutes: 10,
    prompts: [
      'What do you predict will happen?',
      'Why do you think that?',
      'What actually happened?',
      'Was your prediction supported?',
      'What scientific idea could explain the result?',
    ],
  }),
  set({
    id: 'bank-sci-32',
    name: 'Identify the Variables',
    subject: 'Science',
    years: '7–8',
    skill: 'Investigations',
    minutes: 8,
    prompts: [
      'What question are you investigating?',
      'What will you change?',
      'What will you measure?',
      'What needs to stay the same?',
      'Why do these things need to stay the same?',
      'How will you make the test fair?',
    ],
  }),
  set({
    id: 'bank-sci-33',
    name: 'Plan an Investigation',
    subject: 'Science',
    years: '7–8',
    skill: 'Investigations',
    minutes: 12,
    prompts: [
      'What question are you investigating?',
      'What is your hypothesis?',
      'What will you change?',
      'What will you measure?',
      'What will you keep the same?',
      'What equipment will you need?',
      'What data will you collect?',
    ],
  }),
  set({
    id: 'bank-sci-34',
    name: 'Claim–Evidence–Reasoning',
    subject: 'Science',
    years: '9–10',
    skill: 'Scientific explanation',
    minutes: 10,
    prompts: [
      'What claim can you make?',
      'Which evidence supports the claim?',
      'Which scientific concept helps explain the evidence?',
      'How does the evidence support your claim?',
      'Is there any evidence that does not fit?',
      'Write a clear conclusion.',
    ],
  }),
  set({
    id: 'bank-sci-35',
    name: 'Interpret Scientific Data',
    subject: 'Science',
    years: '7–10',
    skill: 'Data analysis',
    minutes: 10,
    prompts: [
      'What trend or pattern can you identify?',
      'Which evidence supports your observation?',
      'Are there any unusual results?',
      'How strong is the pattern?',
      'What scientific explanation could account for it?',
      'What conclusion can you draw?',
    ],
  }),
  set({
    id: 'bank-sci-36',
    name: 'Evaluate an Investigation',
    subject: 'Science',
    years: '9–10',
    skill: 'Investigations',
    minutes: 12,
    prompts: [
      'How reliable are the results?',
      'Are there any unusual or inconsistent results?',
      'What sources of error may have affected the investigation?',
      'Was the method suitable for answering the question?',
      'What could be improved?',
      'What further investigation would strengthen the conclusion?',
    ],
  }),
  set({
    id: 'bank-sci-37',
    name: 'Build a Scientific Explanation',
    subject: 'Science',
    years: '7–10',
    skill: 'Scientific writing',
    minutes: 10,
    prompts: [
      'What phenomenon are you explaining?',
      'Which scientific ideas are relevant?',
      'What evidence or example can you use?',
      'Explain how the evidence connects to the science.',
      'Use scientific vocabulary accurately.',
      'Finish with a clear explanation of why the phenomenon occurs.',
    ],
  }),
  set({
    id: 'bank-sci-38',
    name: 'Evaluate Scientific Evidence',
    subject: 'Science',
    years: '11–12',
    skill: 'Senior science',
    minutes: 15,
    prompts: [
      'What claim or conclusion is being made?',
      'What evidence supports it?',
      'How reliable is the evidence?',
      'What uncertainty, error or limitation is present?',
      'How valid is the conclusion?',
      'Are there alternative explanations?',
      'What additional evidence would strengthen the claim?',
    ],
  }),

  // General — 10
  set({
    id: 'bank-gen-39',
    name: 'Retrieval Warm-Up',
    subject: 'General',
    years: 'All',
    skill: 'Lesson opener',
    minutes: 8,
    prompts: [
      'What can you remember from the last lesson?',
      'Write three important ideas.',
      'Give one example.',
      'Which idea are you least certain about?',
      'Write one question you still have.',
    ],
  }),
  set({
    id: 'bank-gen-40',
    name: 'Confidence Check',
    subject: 'General',
    years: 'All',
    skill: 'Formative check',
    minutes: 5,
    prompts: [
      'How confident are you right now? 1–5',
      'What part feels easiest?',
      'What part are you unsure about?',
      'What would help move your confidence up one point?',
    ],
  }),
  set({
    id: 'bank-gen-41',
    name: 'Find the Misconception',
    subject: 'General',
    years: 'All',
    skill: 'Understanding check',
    minutes: 8,
    note: 'Works best with a statement or example on the board.',
    prompts: [
      'Read the statement or example carefully.',
      'What do you think is incorrect?',
      'Explain why.',
      'What should the correct idea be?',
      'What mistake might have caused the misunderstanding?',
    ],
  }),
  set({
    id: 'bank-gen-42',
    name: 'Exit Understanding Check',
    subject: 'General',
    years: 'All',
    skill: 'Lesson close',
    minutes: 6,
    prompts: [
      'What is the most important thing you learned?',
      'Explain it in your own words.',
      'Give an example.',
      'What can you now do that you could not do before?',
      'What are you still unsure about?',
    ],
  }),
  set({
    id: 'bank-gen-43',
    name: 'Peer Feedback',
    subject: 'General',
    years: '7–12',
    skill: 'Feedback',
    minutes: 8,
    note: 'Works best when students can see a peer’s work.',
    prompts: [
      'What is working well in this piece?',
      'Point to one specific example.',
      'Where could the writer make their meaning clearer?',
      'What is one question you have for the writer?',
      'Give one useful suggestion for the next draft.',
    ],
  }),
  set({
    id: 'bank-gen-44',
    name: 'Draft → Feedback → Redraft',
    subject: 'General',
    years: '7–12',
    skill: 'Writing & feedback',
    minutes: 12,
    note: 'Use after you have commented, or as a structure for Inbox feedback.',
    prompts: [
      'Identify the section you want feedback on.',
      "Read your teacher's comment or note.",
      'What is the feedback asking you to improve?',
      'Explain what you plan to change.',
      'Make the revision.',
      'How has your revision improved the work?',
    ],
  }),
  set({
    id: 'bank-gen-45',
    name: 'Unpack a Key Word',
    subject: 'General',
    years: '5–10',
    skill: 'Vocabulary',
    minutes: 8,
    prompts: [
      'What do you think this word means?',
      'Put the meaning into your own words.',
      'Use the word in a sentence.',
      'What other words have a similar meaning?',
      'What is an example of it?',
      "What is something people might think it means, but it doesn't?",
    ],
  }),
  set({
    id: 'bank-gen-46',
    name: 'Compare & Contrast',
    subject: 'General',
    years: '5–10',
    skill: 'Thinking routine',
    minutes: 8,
    prompts: [
      'What do the two things have in common?',
      'What is one important difference?',
      'Find another difference.',
      'Which difference matters most?',
      'Why?',
      'What conclusion can you make from the comparison?',
    ],
  }),
  set({
    id: 'bank-gen-47',
    name: 'Independent Work Check-In',
    subject: 'General',
    years: 'All',
    skill: 'Live monitoring',
    minutes: 5,
    prompts: [
      'What are you working on right now?',
      'What have you completed?',
      'What are you working on next?',
      'Are you stuck anywhere?',
      'If you are stuck, explain exactly where.',
      'What do you need from your teacher?',
    ],
  }),
  set({
    id: 'bank-gen-48',
    name: 'Teach It Back',
    subject: 'General',
    years: 'All',
    skill: 'Understanding',
    minutes: 8,
    prompts: [
      'Explain the idea as if you were teaching someone who missed the lesson.',
      'What are the most important things they need to know?',
      'Give an example.',
      'What mistake should they avoid?',
      'What question would you ask to check whether they understood?',
    ],
  }),
];

const YEAR_ORDER = ['5–6', '7–8', '9–10', '11–12'];

function expandYears(label) {
  const raw = String(label || '').replace(/-/g, '–').trim();
  if (!raw || raw === 'All') return new Set(YEAR_ORDER);
  if (YEAR_ORDER.includes(raw)) return new Set([raw]);
  const match = raw.match(/^(\d+)–(\d+)$/);
  if (!match) return new Set(YEAR_ORDER);
  const start = Number(match[1]);
  const end = Number(match[2]);
  const covered = new Set();
  for (const band of YEAR_ORDER) {
    const [a, b] = band.split('–').map(Number);
    if (a <= end && b >= start) covered.add(band);
  }
  return covered.size ? covered : new Set(YEAR_ORDER);
}

export function setMatchesFilters(set, subject, yearBand) {
  if (subject && subject !== 'All' && set.subject !== subject) return false;
  if (!yearBand || yearBand === 'All') return true;
  return expandYears(set.years).has(yearBand);
}

export function formatSetMeta(set) {
  const years = set.years === 'All' ? 'All years' : `Years ${set.years}`;
  const mins = set.minutes ? `~${set.minutes} min` : '';
  return [set.subject, years, set.skill, mins].filter(Boolean).join(' · ');
}
